---
- name: Create Caddy group
  group: name=caddy

- name: Create Caddy user
  user: name=caddy group=caddy home=/ system=yes

- name: Create dir to unpack Caddy archive
  file: path=/root/caddy-dist state=directory

- name: Create dir to store SSL certificates
  file: path=/etc/ssl/caddy state=directory owner=caddy group=caddy

- name: Create configuration directory
  file: path=/etc/caddy state=directory

- name: Create dir to store service config files
  file: path=/etc/caddy/services.d state=directory

- name: Download Caddy package
  unarchive: src=caddy_linux_amd64_custom.tar.gz dest=/root/caddy-dist/

- name: Install Caddy binary
  copy: remote_src=yes src=/root/caddy-dist/caddy dest=/usr/local/bin/caddy

- name: Set NET BIND capability
  capabilities: path=/usr/local/bin/caddy capability=cap_net_bind_service+ep state=present

- name: Add systemd service
  copy: src=caddy.service dest=/etc/systemd/system/
  notify: reload daemons

- name: Enable and start Caddy
  systemd: name=caddy enabled=yes state=started daemon_reload=yes

