---
# Users in the ssl group can read certificates and private keys.
- group: name=ssl
- user: name=ssl group=ssl
- yum: pkg=certbot
- file: path=/var/log/letsencrypt state=directory owner=ssl group=ssl mode=0750
- file: path=/etc/letsencrypt/archive state=directory owner=ssl group=ssl mode=0750
- file: path=/etc/letsencrypt/live state=directory owner=ssl group=ssl mode=0750
- file: path=/var/acme state=directory owner=ssl group=ssl mode=0750
