---
- name: set up server
  user: root
  hosts: helpdesk
  vars_files:
    - ssl_keys.vault
  roles:
    - { role: base, tags: ['base'] }
    - { role: caddy, tags: ['caddy'] }
    - { role: helpdesk, tags: ['helpdesk'] }
